spring:
  application:
    name: dubbo-provider
  aop:
    proxy-target-class: true
  dubbo:
    appname: dubbo-provider
    protocol: dubbo
    port: 20882
    version: 1.0.0
    registry: zookeeper://127.0.0.1:2181