spring:
  application:
    name: dubbo-consumer
  aop:
    proxy-target-class: true
  dubbo:
    appname: dubbo-consumer
    protocol: dubbo
    port: 20882
    version: 1.0.0
    registry: zookeeper://192.168.0.184:2181